project:
  type: website
  output-dir: docs

website:
  title: "Cheng-Yuan Wu's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: Resume.qmd
        text: Resume
      - href: blog.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show Code"
    thebe: true

# execute:
#   echo: true
#   eval: true
#   output: true



